// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoRo7-iDIzv1yLw2kjqKndocGx1lnAUhA',
    appId: '1:228897062810:web:2c695170d514cda094c423',
    messagingSenderId: '228897062810',
    projectId: 'to-do-list-9e7c0',
    authDomain: 'to-do-list-9e7c0.firebaseapp.com',
    storageBucket: 'to-do-list-9e7c0.appspot.com',
    measurementId: 'G-QKNDLCB1E7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiiBEPNJMxvc-dhpEPD_7n_vbGmI3DyWo',
    appId: '1:228897062810:android:6ca84fe282ce371a94c423',
    messagingSenderId: '228897062810',
    projectId: 'to-do-list-9e7c0',
    storageBucket: 'to-do-list-9e7c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCElCD6L8qVHqH6JBrqgk45qVJd5O--32o',
    appId: '1:228897062810:ios:30e3f6b4e254f98c94c423',
    messagingSenderId: '228897062810',
    projectId: 'to-do-list-9e7c0',
    storageBucket: 'to-do-list-9e7c0.appspot.com',
    iosBundleId: 'com.example.toDoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCElCD6L8qVHqH6JBrqgk45qVJd5O--32o',
    appId: '1:228897062810:ios:30e3f6b4e254f98c94c423',
    messagingSenderId: '228897062810',
    projectId: 'to-do-list-9e7c0',
    storageBucket: 'to-do-list-9e7c0.appspot.com',
    iosBundleId: 'com.example.toDoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoRo7-iDIzv1yLw2kjqKndocGx1lnAUhA',
    appId: '1:228897062810:web:73056ec36d0339c894c423',
    messagingSenderId: '228897062810',
    projectId: 'to-do-list-9e7c0',
    authDomain: 'to-do-list-9e7c0.firebaseapp.com',
    storageBucket: 'to-do-list-9e7c0.appspot.com',
    measurementId: 'G-81VPV7YFM9',
  );
}
